# Generated by Django 4.0.6 on 2022-07-07 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trail',
            name='imageUrl',
            field=models.URLField(max_length=500),
        ),
    ]
