# Generated by Django 4.0.6 on 2022-07-08 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_trail_imageurl'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trail',
            old_name='trail',
            new_name='name',
        ),
    ]
