# Generated by Django 4.0.6 on 2022-07-08 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_trail_trail_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trail',
            name='duration',
            field=models.CharField(default='', max_length=20),
        ),
    ]
